INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (2,'Baja California');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (3,'Baja California Sur');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (4,'Campeche');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (5,'Coahuila');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (6,'Colima');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (7,'Chiapas');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (8,'Chihuahua');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (9,'Ciudad de México');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (10,'Durango');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (11,'Guanajuato');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (12,'Guerrero');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (13,'Hidalgo');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (14,'Jalisco');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (15,'México');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (16,'Michocán');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (17,'Morelos');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (18,'Nayarit');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (19,'Nuevo León');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (20,'Oaxaca');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (21,'Puebla');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (22,'Querétaro');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (23,'San Luis Potosí');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (24,'Sinaloa');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (25,'Sonora');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (26,'Tabasco');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (27,'Tamaulipas');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (28,'Tlaxcala');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (29,'Veracruz');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (30,'Yucatán');
INSERT INTO `estado`(`idEstado`, `nombreEstado`) VALUES (31,'Zacatecas');

